# Symlink first to /etc/keyd/default.conf
# sudo ln -s $HOME/.local/share/keyd/default.conf /etc/keyd/default.conf
[ids]

*

[main]

# Maps capslock to escape when pressed and control when held.
capslock = overload(control, esc)
