#!/bin/sh

# Source xprofile to avoid doubling up commands
if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.xprofile"
fi

systemctl --user import-environment DISPLAY
DEFAULT_SESSION='i3 --shmlog-size 0'

dbus-update-activation-environment --all
exec $DEFAULT_SESSION
