#!/bin/sh

# This file runs when a DM logs you into a graphical session.

xrandr --dpi 96		# Set DPI: Larger number for larger screens.
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	

# mpd xcompmgr dunst unclutter pipewire remapd
autostart="remapd"

for program in $autostart; do
	pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
