# Autostart
# exec-once = command will execute only on launch
# exec = command will execute on each reload
# exec-shutdown = command will execute only on shutdown
exec-once = $HOME/.config/hypr/xdg-portal-hyprland
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user restart mpd.service
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = pypr
exec-once = blueman-applet
exec-once = nm-applet --indicator
exec-once = copyq --start-server
exec-once = udiskie
exec-once = fusuma
exec-once = waybar
exec-once = hypridle
exec-once = $HOME/.local/bin/tmux-sessions
exec-once = /usr/bin/kdeconnectd
exec-once = /usr/bin/kdeconnect-indicator
exec-once = brightnessctl s +0.1%
exec-once = avizo-service
exec-once = anacron -t /home/$USER/.local/etc/anacrontab -S /home/$USER/.local/.var/spool/anacron
exec-once = hyprsunset -t 5700
exec-once = $HOME/.config/hypr/scripts/pick_wallpaper.sh; hyprpaper
exec-once = sleep 2; hyprctl reload
# exec-once = easyeffects --gapplication-service
# exec-once = keyd-application-mapper -d
