# $laptop = LVDS-1
# $external = VGA-1
# monitor=$laptop,1366x768,auto,1
# monitor=$external,1024x768,0x0,1
# # monitor=,preferred,0x0,1
#
# # Bind Workspaces to each display
# workspace = 1, monitor:$external
# workspace = 2, monitor:$external
# workspace = 3, monitor:$laptop
# workspace = 4, monitor:$laptop

# change monitor to high resolution, the last argument is the scale factor
monitor=,highres,auto,1.20

source = $HOME/.cache/wal/hypr.conf
source = $HOME/.config/hypr/autostart.conf
source = $HOME/.config/hypr/env.conf

# unscale XWayland
xwayland {
  force_zero_scaling = true
}

# For all categories, see https://wiki.hyprland.org/Configuring/Variables/
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options = ctrl:nocaps
    kb_rules =
    repeat_rate = 62
    repeat_delay = 190

    follow_mouse = 1

    touchpad {
        natural_scroll = false
    }

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

general {
    gaps_in = 0
    gaps_out = 2
    border_size = 2
    # col.active_border = rgba(ff000000) rgba(ffffffff) rgba(ff000000) rgba(ffffffff) 45deg
    col.active_border = $color0 $color1 45deg
    col.inactive_border = $color0
    # col.inactive_border = rgba(11707b7c)
    
    # col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    # col.inactive_border = rgba(595959aa)
    layout = master
    allow_tearing = false
    resize_on_border = true
    hover_icon_on_border = true
}

cursor {
    inactive_timeout = 3
}

decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    rounding = 8

    blur {
        enabled = true
        size = 3
        passes = 1
        
        vibrancy = 0.1696
    }

    # drop_shadow = false
    # shadow_range = 4
    # shadow_render_power = 3
    # col.shadow = rgba(1a1a1aee)

    dim_inactive = false
    dim_strength = 0.1
    dim_around = 0.4 # for Floating windows
}

animations {
    enabled = true

    # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

    # bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    # animation = NAME, ONOFF, SPEED, CURVE

    animation = windows, 1, 2, default
    animation = windowsIn, 1, 2, default
    animation = windowsOut, 0, 3, default, popin 80%
    animation = border, 0, 3, default
    animation = borderangle, 0, 3, default
    animation = fade, 1, 6, default
    animation = workspaces, 1, 2, default
}

dwindle {
    # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    pseudotile = true # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # you probably want this
}

master {
    # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    # new_status = master # set new window as master
    new_on_top = false
    allow_small_split = false
    # Split factor
    mfact = 0.55
}

gestures {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    workspace_swipe = false
}

misc {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
    enable_swallow = true
    swallow_regex = (scratchpadttrm)|(Alacritty)|(kitty)
}

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
device {
    name = 2-synaptics-touchpad
    sensitivity = -0.5
}

source = $HOME/.config/hypr/binds.conf
source = $HOME/.config/hypr/media-binds.conf
source = $HOME/.config/hypr/windowrules.conf
