wallpaper {
    monitor = eDP-1
    path = $HOME/wallpapers/goku-musculoso-dragon-ball-z-amoled-minimal-black-1920x1200-4945.png

}

wallpaper {
    monitor = HDMI-A-1
    path = $HOME/wallpapers/porsche-911-2560x1440-13014.jpg
}
