# Symlink first to /etc/keyd/default.conf
# sudo ln -s $HOME/.local/share/keyd/default.conf /etc/keyd/default.conf
[ids]
*

[main]

# Maps capslock to escape when pressed control when held.
# Ref: https://github.com/rvaiya/keyd/blob/9c758c0e152426cab3972256282bc7ee7e2f808e/docs/keyd.scdoc#L705and
capslock = overloadt2(capslock, esc, 140)
# esc = capslock

[capslock:C]
h = left
k = up
j = down
l = right
i = C-right
# Tmux specific macro layer
c = macro(C-space c)
m = macro(C-space C-m)
n = macro(C-space n)
p = macro(C-space p)
s = macro(C-space s)
